### ISSUE TITLE
Extension error after screen turns off for a long time

### ISSUE THREAD

**Issue by yukina3230** [vixalien/gnome-shell-extension-awake#1]
When the screen is off for a long time, I noticed Keep Awake toggle button disappeared from quick settings, then i check extension manager and it shows "this.sessionManager is null" error

![Screenshot from 2023-02-07 01-46-49](https://user-images.githubusercontent.com/75545944/217068006-79d9a9bc-4719-4dad-b27b-2ea5c8b8f6cc.png)

**Comment by vixalien** [comment]
that has been fixed in v4! try updating and check again!
